// Generated by tools/build-fonts.py — do not edit by hand.
// Official Roblox font families (rbxasset://fonts/families/*.json).
export const FONT_FAMILIES = [
 {
  "name": "Accanthis ADF Std",
  "id": "AccanthisADFStd",
  "asset": "rbxasset://fonts/families/AccanthisADFStd.json",
  "faces": [],
  "approx": "Merriweather"
 },
 {
  "name": "Amatic SC",
  "id": "AmaticSC",
  "asset": "rbxasset://fonts/families/AmaticSC.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "AmaticSC/400-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "AmaticSC/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1016,
   "hheaDescent": -245,
   "hheaLineGap": 0,
   "typoAscent": 1016,
   "typoDescent": -245,
   "typoLineGap": 0,
   "winAscent": 1139,
   "winDescent": 265,
   "capHeight": 754,
   "xHeight": 659,
   "useTypo": true
  }
 },
 {
  "name": "Arimo",
  "id": "Arimo",
  "asset": "rbxasset://fonts/families/Arimo.json",
  "faces": [
   {
    "weight": 400,
    "style": "Italic",
    "file": "Arimo/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Arimo/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "Arimo/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Arimo/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "Arimo/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Arimo/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "Arimo/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Arimo/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 1854,
   "hheaDescent": -434,
   "hheaLineGap": 67,
   "typoAscent": 1854,
   "typoDescent": -434,
   "typoLineGap": 67,
   "winAscent": 2136,
   "winDescent": 797,
   "capHeight": 1409,
   "xHeight": 1082,
   "useTypo": true
  }
 },
 {
  "name": "Balthazar",
  "id": "Balthazar",
  "asset": "rbxasset://fonts/families/Balthazar.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "Balthazar/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 796,
   "hheaDescent": -222,
   "hheaLineGap": 0,
   "typoAscent": 796,
   "typoDescent": -222,
   "typoLineGap": 0,
   "winAscent": 796,
   "winDescent": 222,
   "capHeight": 605,
   "xHeight": 399,
   "useTypo": false
  }
 },
 {
  "name": "Bangers",
  "id": "Bangers",
  "asset": "rbxasset://fonts/families/Bangers.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "Bangers/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 883,
   "hheaDescent": -181,
   "hheaLineGap": 0,
   "typoAscent": 883,
   "typoDescent": -181,
   "typoLineGap": 0,
   "winAscent": 1401,
   "winDescent": 356,
   "capHeight": 721,
   "xHeight": 721,
   "useTypo": true
  }
 },
 {
  "name": "Builder Extended",
  "id": "BuilderExtended",
  "asset": "rbxasset://fonts/families/BuilderExtended.json",
  "faces": [],
  "approx": "Michroma"
 },
 {
  "name": "Builder Mono",
  "id": "BuilderMono",
  "asset": "rbxasset://fonts/families/BuilderMono.json",
  "faces": [],
  "approx": "Roboto Mono"
 },
 {
  "name": "Builder Sans",
  "id": "BuilderSans",
  "asset": "rbxasset://fonts/families/BuilderSans.json",
  "faces": [],
  "approx": "Arimo"
 },
 {
  "name": "Comic Neue Angular",
  "id": "ComicNeueAngular",
  "asset": "rbxasset://fonts/families/ComicNeueAngular.json",
  "faces": [
   {
    "weight": 300,
    "style": "Italic",
    "file": "ComicNeueAngular/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "ComicNeueAngular/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "ComicNeueAngular/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "ComicNeueAngular/400-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "ComicNeueAngular/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "ComicNeueAngular/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 900,
   "hheaDescent": -250,
   "hheaLineGap": 0,
   "typoAscent": 900,
   "typoDescent": -250,
   "typoLineGap": 0,
   "winAscent": 1000,
   "winDescent": 350,
   "capHeight": 670,
   "xHeight": 487,
   "useTypo": true
  }
 },
 {
  "name": "Creepster",
  "id": "Creepster",
  "asset": "rbxasset://fonts/families/Creepster.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "Creepster/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1024,
   "hheaAscent": 974,
   "hheaDescent": -223,
   "hheaLineGap": 0,
   "typoAscent": 974,
   "typoDescent": -223,
   "typoLineGap": 0,
   "winAscent": 974,
   "winDescent": 223,
   "capHeight": 751,
   "xHeight": 751,
   "useTypo": false
  }
 },
 {
  "name": "Denk One",
  "id": "DenkOne",
  "asset": "rbxasset://fonts/families/DenkOne.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "DenkOne/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 2118,
   "hheaDescent": -442,
   "hheaLineGap": 0,
   "typoAscent": 2118,
   "typoDescent": -442,
   "typoLineGap": 0,
   "winAscent": 2631,
   "winDescent": 609,
   "capHeight": 1690,
   "xHeight": 1202,
   "useTypo": true
  }
 },
 {
  "name": "Fondamento",
  "id": "Fondamento",
  "asset": "rbxasset://fonts/families/Fondamento.json",
  "faces": [
   {
    "weight": 400,
    "style": "Italic",
    "file": "Fondamento/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Fondamento/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 2060,
   "hheaDescent": -774,
   "hheaLineGap": 0,
   "typoAscent": 2060,
   "typoDescent": -774,
   "typoLineGap": 0,
   "winAscent": 2060,
   "winDescent": 774,
   "capHeight": 1439,
   "xHeight": 953,
   "useTypo": false
  }
 },
 {
  "name": "Fredoka One",
  "id": "FredokaOne",
  "asset": "rbxasset://fonts/families/FredokaOne.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "FredokaOne/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 974,
   "hheaDescent": -236,
   "hheaLineGap": 0,
   "typoAscent": 974,
   "typoDescent": -236,
   "typoLineGap": 0,
   "winAscent": 974,
   "winDescent": 236,
   "capHeight": 733,
   "xHeight": 527,
   "useTypo": false
  }
 },
 {
  "name": "Grenze Gotisch",
  "id": "GrenzeGotisch",
  "asset": "rbxasset://fonts/families/GrenzeGotisch.json",
  "faces": [
   {
    "weight": 100,
    "style": "Normal",
    "file": "GrenzeGotisch/100-normal.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "GrenzeGotisch/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "GrenzeGotisch/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "GrenzeGotisch/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "GrenzeGotisch/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "GrenzeGotisch/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "GrenzeGotisch/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "GrenzeGotisch/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "GrenzeGotisch/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1100,
   "hheaDescent": -380,
   "hheaLineGap": 0,
   "typoAscent": 1100,
   "typoDescent": -380,
   "typoLineGap": 0,
   "winAscent": 1111,
   "winDescent": 380,
   "capHeight": 603,
   "xHeight": 448,
   "useTypo": true
  }
 },
 {
  "name": "Guru",
  "id": "Guru",
  "asset": "rbxasset://fonts/families/Guru.json",
  "faces": [],
  "approx": "Merriweather"
 },
 {
  "name": "Highway Gothic",
  "id": "HighwayGothic",
  "asset": "rbxasset://fonts/families/HighwayGothic.json",
  "faces": [],
  "approx": "Roboto Condensed"
 },
 {
  "name": "Inconsolata",
  "id": "Inconsolata",
  "asset": "rbxasset://fonts/families/Inconsolata.json",
  "faces": [
   {
    "weight": 200,
    "style": "Normal",
    "file": "Inconsolata/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "Inconsolata/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Inconsolata/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Inconsolata/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Inconsolata/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Inconsolata/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "Inconsolata/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "Inconsolata/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 859,
   "hheaDescent": -190,
   "hheaLineGap": 0,
   "typoAscent": 859,
   "typoDescent": -190,
   "typoLineGap": 0,
   "winAscent": 1004,
   "winDescent": 454,
   "capHeight": 623,
   "xHeight": 457,
   "useTypo": true
  }
 },
 {
  "name": "Indie Flower",
  "id": "IndieFlower",
  "asset": "rbxasset://fonts/families/IndieFlower.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "IndieFlower/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1024,
   "hheaAscent": 994,
   "hheaDescent": -500,
   "hheaLineGap": 0,
   "typoAscent": 994,
   "typoDescent": -500,
   "typoLineGap": 0,
   "winAscent": 994,
   "winDescent": 500,
   "capHeight": 587,
   "xHeight": 374,
   "useTypo": false
  }
 },
 {
  "name": "Josefin Sans",
  "id": "JosefinSans",
  "asset": "rbxasset://fonts/families/JosefinSans.json",
  "faces": [
   {
    "weight": 100,
    "style": "Italic",
    "file": "JosefinSans/100-italic.woff2"
   },
   {
    "weight": 100,
    "style": "Normal",
    "file": "JosefinSans/100-normal.woff2"
   },
   {
    "weight": 200,
    "style": "Italic",
    "file": "JosefinSans/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "JosefinSans/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "JosefinSans/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "JosefinSans/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "JosefinSans/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "JosefinSans/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "JosefinSans/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "JosefinSans/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "JosefinSans/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "JosefinSans/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "JosefinSans/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "JosefinSans/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 750,
   "hheaDescent": -250,
   "hheaLineGap": 0,
   "typoAscent": 750,
   "typoDescent": -250,
   "typoLineGap": 0,
   "winAscent": 1242,
   "winDescent": 324,
   "capHeight": 702,
   "xHeight": 378,
   "useTypo": true
  }
 },
 {
  "name": "Jura",
  "id": "Jura",
  "asset": "rbxasset://fonts/families/Jura.json",
  "faces": [
   {
    "weight": 300,
    "style": "Normal",
    "file": "Jura/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Jura/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Jura/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Jura/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Jura/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2000,
   "hheaAscent": 1930,
   "hheaDescent": -436,
   "hheaLineGap": 0,
   "typoAscent": 1930,
   "typoDescent": -436,
   "typoLineGap": 0,
   "winAscent": 2203,
   "winDescent": 456,
   "capHeight": 1266,
   "xHeight": 922,
   "useTypo": true
  }
 },
 {
  "name": "Kalam",
  "id": "Kalam",
  "asset": "rbxasset://fonts/families/Kalam.json",
  "faces": [
   {
    "weight": 300,
    "style": "Normal",
    "file": "Kalam/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Kalam/400-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Kalam/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1063,
   "hheaDescent": -531,
   "hheaLineGap": 0,
   "typoAscent": 1063,
   "typoDescent": -531,
   "typoLineGap": 0,
   "winAscent": 1063,
   "winDescent": 531,
   "capHeight": 739,
   "xHeight": 526,
   "useTypo": false
  }
 },
 {
  "name": "Luckiest Guy",
  "id": "LuckiestGuy",
  "asset": "rbxasset://fonts/families/LuckiestGuy.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "LuckiestGuy/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 1440,
   "hheaDescent": -608,
   "hheaLineGap": 0,
   "typoAscent": 1440,
   "typoDescent": -608,
   "typoLineGap": 0,
   "winAscent": 2006,
   "winDescent": 504,
   "capHeight": 1424,
   "xHeight": 1400,
   "useTypo": false
  }
 },
 {
  "name": "Merriweather",
  "id": "Merriweather",
  "asset": "rbxasset://fonts/families/Merriweather.json",
  "faces": [
   {
    "weight": 300,
    "style": "Italic",
    "file": "Merriweather/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "Merriweather/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "Merriweather/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Merriweather/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "Merriweather/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Merriweather/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "Merriweather/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Merriweather/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "Merriweather/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Merriweather/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Italic",
    "file": "Merriweather/800-italic.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "Merriweather/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Italic",
    "file": "Merriweather/900-italic.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "Merriweather/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2000,
   "hheaAscent": 1968,
   "hheaDescent": -546,
   "hheaLineGap": 0,
   "typoAscent": 1968,
   "typoDescent": -546,
   "typoLineGap": 0,
   "winAscent": 2476,
   "winDescent": 988,
   "capHeight": 1486,
   "xHeight": 1111,
   "useTypo": true
  }
 },
 {
  "name": "Michroma",
  "id": "Michroma",
  "asset": "rbxasset://fonts/families/Michroma.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "Michroma/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 2368,
   "hheaDescent": -544,
   "hheaLineGap": 0,
   "typoAscent": 2368,
   "typoDescent": -544,
   "typoLineGap": 0,
   "winAscent": 3040,
   "winDescent": 576,
   "capHeight": 1536,
   "xHeight": 1152,
   "useTypo": true
  }
 },
 {
  "name": "Montserrat",
  "id": "Montserrat",
  "asset": "rbxasset://fonts/families/Montserrat.json",
  "faces": [
   {
    "weight": 100,
    "style": "Italic",
    "file": "Montserrat/100-italic.woff2"
   },
   {
    "weight": 100,
    "style": "Normal",
    "file": "Montserrat/100-normal.woff2"
   },
   {
    "weight": 200,
    "style": "Italic",
    "file": "Montserrat/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "Montserrat/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "Montserrat/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "Montserrat/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "Montserrat/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Montserrat/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "Montserrat/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Montserrat/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "Montserrat/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Montserrat/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "Montserrat/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Montserrat/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Italic",
    "file": "Montserrat/800-italic.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "Montserrat/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Italic",
    "file": "Montserrat/900-italic.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "Montserrat/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 968,
   "hheaDescent": -251,
   "hheaLineGap": 0,
   "typoAscent": 968,
   "typoDescent": -251,
   "typoLineGap": 0,
   "winAscent": 1109,
   "winDescent": 453,
   "capHeight": 700,
   "xHeight": 525,
   "useTypo": true
  }
 },
 {
  "name": "Nunito",
  "id": "Nunito",
  "asset": "rbxasset://fonts/families/Nunito.json",
  "faces": [
   {
    "weight": 200,
    "style": "Italic",
    "file": "Nunito/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "Nunito/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "Nunito/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "Nunito/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "Nunito/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Nunito/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "Nunito/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Nunito/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "Nunito/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Nunito/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "Nunito/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Nunito/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Italic",
    "file": "Nunito/800-italic.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "Nunito/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Italic",
    "file": "Nunito/900-italic.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "Nunito/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1011,
   "hheaDescent": -353,
   "hheaLineGap": 0,
   "typoAscent": 1011,
   "typoDescent": -353,
   "typoLineGap": 0,
   "winAscent": 1077,
   "winDescent": 300,
   "capHeight": 705,
   "xHeight": 484,
   "useTypo": true
  }
 },
 {
  "name": "Oswald",
  "id": "Oswald",
  "asset": "rbxasset://fonts/families/Oswald.json",
  "faces": [
   {
    "weight": 200,
    "style": "Normal",
    "file": "Oswald/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "Oswald/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Oswald/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Oswald/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Oswald/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Oswald/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1193,
   "hheaDescent": -289,
   "hheaLineGap": 0,
   "typoAscent": 1193,
   "typoDescent": -289,
   "typoLineGap": 0,
   "winAscent": 1325,
   "winDescent": 377,
   "capHeight": 810,
   "xHeight": 578,
   "useTypo": true
  }
 },
 {
  "name": "Patrick Hand",
  "id": "PatrickHand",
  "asset": "rbxasset://fonts/families/PatrickHand.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "PatrickHand/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1042,
   "hheaDescent": -312,
   "hheaLineGap": 0,
   "typoAscent": 1024,
   "typoDescent": -312,
   "typoLineGap": 0,
   "winAscent": 1042,
   "winDescent": 312,
   "capHeight": 661,
   "xHeight": 467,
   "useTypo": false
  }
 },
 {
  "name": "Permanent Marker",
  "id": "PermanentMarker",
  "asset": "rbxasset://fonts/families/PermanentMarker.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "PermanentMarker/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1024,
   "hheaAscent": 1136,
   "hheaDescent": -325,
   "hheaLineGap": 31,
   "typoAscent": 622,
   "typoDescent": -61,
   "typoLineGap": 61,
   "winAscent": 1136,
   "winDescent": 325,
   "capHeight": 758,
   "xHeight": 625,
   "useTypo": false
  }
 },
 {
  "name": "Press Start 2P",
  "id": "PressStart2P",
  "asset": "rbxasset://fonts/families/PressStart2P.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "PressStart2P/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1000,
   "hheaDescent": 0,
   "hheaLineGap": 0,
   "typoAscent": 1000,
   "typoDescent": 0,
   "typoLineGap": 0,
   "winAscent": 1000,
   "winDescent": 374,
   "capHeight": 1000,
   "xHeight": 750,
   "useTypo": true
  }
 },
 {
  "name": "Roboto",
  "id": "Roboto",
  "asset": "rbxasset://fonts/families/Roboto.json",
  "faces": [
   {
    "weight": 100,
    "style": "Italic",
    "file": "Roboto/100-italic.woff2"
   },
   {
    "weight": 100,
    "style": "Normal",
    "file": "Roboto/100-normal.woff2"
   },
   {
    "weight": 200,
    "style": "Italic",
    "file": "Roboto/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "Roboto/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "Roboto/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "Roboto/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "Roboto/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Roboto/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "Roboto/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Roboto/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "Roboto/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Roboto/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "Roboto/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Roboto/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Italic",
    "file": "Roboto/800-italic.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "Roboto/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Italic",
    "file": "Roboto/900-italic.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "Roboto/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 1900,
   "hheaDescent": -500,
   "hheaLineGap": 0,
   "typoAscent": 1536,
   "typoDescent": -512,
   "typoLineGap": 102,
   "winAscent": 1946,
   "winDescent": 512,
   "capHeight": 1456,
   "xHeight": 1082,
   "useTypo": false
  }
 },
 {
  "name": "Roboto Condensed",
  "id": "RobotoCondensed",
  "asset": "rbxasset://fonts/families/RobotoCondensed.json",
  "faces": [
   {
    "weight": 100,
    "style": "Italic",
    "file": "RobotoCondensed/100-italic.woff2"
   },
   {
    "weight": 100,
    "style": "Normal",
    "file": "RobotoCondensed/100-normal.woff2"
   },
   {
    "weight": 200,
    "style": "Italic",
    "file": "RobotoCondensed/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "RobotoCondensed/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "RobotoCondensed/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "RobotoCondensed/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "RobotoCondensed/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "RobotoCondensed/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "RobotoCondensed/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "RobotoCondensed/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "RobotoCondensed/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "RobotoCondensed/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "RobotoCondensed/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "RobotoCondensed/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Italic",
    "file": "RobotoCondensed/800-italic.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "RobotoCondensed/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Italic",
    "file": "RobotoCondensed/900-italic.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "RobotoCondensed/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 1900,
   "hheaDescent": -500,
   "hheaLineGap": 0,
   "typoAscent": 1536,
   "typoDescent": -512,
   "typoLineGap": 102,
   "winAscent": 1946,
   "winDescent": 512,
   "capHeight": 1456,
   "xHeight": 1082,
   "useTypo": false
  }
 },
 {
  "name": "Roboto Mono",
  "id": "RobotoMono",
  "asset": "rbxasset://fonts/families/RobotoMono.json",
  "faces": [
   {
    "weight": 100,
    "style": "Italic",
    "file": "RobotoMono/100-italic.woff2"
   },
   {
    "weight": 100,
    "style": "Normal",
    "file": "RobotoMono/100-normal.woff2"
   },
   {
    "weight": 200,
    "style": "Italic",
    "file": "RobotoMono/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "RobotoMono/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "RobotoMono/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "RobotoMono/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "RobotoMono/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "RobotoMono/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "RobotoMono/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "RobotoMono/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "RobotoMono/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "RobotoMono/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "RobotoMono/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "RobotoMono/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 2146,
   "hheaDescent": -555,
   "hheaLineGap": 0,
   "typoAscent": 2146,
   "typoDescent": -555,
   "typoLineGap": 0,
   "winAscent": 2146,
   "winDescent": 555,
   "capHeight": 1456,
   "xHeight": 1082,
   "useTypo": false
  }
 },
 {
  "name": "Roman Antique",
  "id": "RomanAntique",
  "asset": "rbxasset://fonts/families/RomanAntique.json",
  "faces": [],
  "approx": "Fondamento"
 },
 {
  "name": "Sarpanch",
  "id": "Sarpanch",
  "asset": "rbxasset://fonts/families/Sarpanch.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "Sarpanch/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Sarpanch/500-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "Sarpanch/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Sarpanch/700-normal.woff2"
   },
   {
    "weight": 800,
    "style": "Normal",
    "file": "Sarpanch/800-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "Sarpanch/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1050,
   "hheaDescent": -350,
   "hheaLineGap": 0,
   "typoAscent": 1050,
   "typoDescent": -350,
   "typoLineGap": 0,
   "winAscent": 1050,
   "winDescent": 350,
   "capHeight": 622,
   "xHeight": 485,
   "useTypo": true
  }
 },
 {
  "name": "Source Sans Pro",
  "id": "SourceSansPro",
  "asset": "rbxasset://fonts/families/SourceSansPro.json",
  "faces": [
   {
    "weight": 200,
    "style": "Italic",
    "file": "SourceSansPro/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "SourceSansPro/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "SourceSansPro/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "SourceSansPro/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "SourceSansPro/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "SourceSansPro/400-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "SourceSansPro/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "SourceSansPro/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "SourceSansPro/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "SourceSansPro/700-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Italic",
    "file": "SourceSansPro/900-italic.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "SourceSansPro/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 984,
   "hheaDescent": -273,
   "hheaLineGap": 0,
   "typoAscent": 750,
   "typoDescent": -250,
   "typoLineGap": 0,
   "winAscent": 984,
   "winDescent": 273,
   "capHeight": 660,
   "xHeight": 486,
   "useTypo": false
  }
 },
 {
  "name": "Special Elite",
  "id": "SpecialElite",
  "asset": "rbxasset://fonts/families/SpecialElite.json",
  "faces": [
   {
    "weight": 400,
    "style": "Normal",
    "file": "SpecialElite/400-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 2048,
   "hheaAscent": 1440,
   "hheaDescent": -608,
   "hheaLineGap": 0,
   "typoAscent": 1440,
   "typoDescent": -608,
   "typoLineGap": 0,
   "winAscent": 1440,
   "winDescent": 608,
   "capHeight": 713,
   "xHeight": 528,
   "useTypo": false
  }
 },
 {
  "name": "Titillium Web",
  "id": "TitilliumWeb",
  "asset": "rbxasset://fonts/families/TitilliumWeb.json",
  "faces": [
   {
    "weight": 200,
    "style": "Italic",
    "file": "TitilliumWeb/200-italic.woff2"
   },
   {
    "weight": 200,
    "style": "Normal",
    "file": "TitilliumWeb/200-normal.woff2"
   },
   {
    "weight": 300,
    "style": "Italic",
    "file": "TitilliumWeb/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "TitilliumWeb/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "TitilliumWeb/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "TitilliumWeb/400-normal.woff2"
   },
   {
    "weight": 600,
    "style": "Italic",
    "file": "TitilliumWeb/600-italic.woff2"
   },
   {
    "weight": 600,
    "style": "Normal",
    "file": "TitilliumWeb/600-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "TitilliumWeb/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "TitilliumWeb/700-normal.woff2"
   },
   {
    "weight": 900,
    "style": "Normal",
    "file": "TitilliumWeb/900-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 1133,
   "hheaDescent": -388,
   "hheaLineGap": 0,
   "typoAscent": 1133,
   "typoDescent": -388,
   "typoLineGap": 0,
   "winAscent": 1133,
   "winDescent": 388,
   "capHeight": 692,
   "xHeight": 500,
   "useTypo": false
  }
 },
 {
  "name": "Ubuntu",
  "id": "Ubuntu",
  "asset": "rbxasset://fonts/families/Ubuntu.json",
  "faces": [
   {
    "weight": 300,
    "style": "Italic",
    "file": "Ubuntu/300-italic.woff2"
   },
   {
    "weight": 300,
    "style": "Normal",
    "file": "Ubuntu/300-normal.woff2"
   },
   {
    "weight": 400,
    "style": "Italic",
    "file": "Ubuntu/400-italic.woff2"
   },
   {
    "weight": 400,
    "style": "Normal",
    "file": "Ubuntu/400-normal.woff2"
   },
   {
    "weight": 500,
    "style": "Italic",
    "file": "Ubuntu/500-italic.woff2"
   },
   {
    "weight": 500,
    "style": "Normal",
    "file": "Ubuntu/500-normal.woff2"
   },
   {
    "weight": 700,
    "style": "Italic",
    "file": "Ubuntu/700-italic.woff2"
   },
   {
    "weight": 700,
    "style": "Normal",
    "file": "Ubuntu/700-normal.woff2"
   }
  ],
  "approx": null,
  "metrics": {
   "upm": 1000,
   "hheaAscent": 932,
   "hheaDescent": -189,
   "hheaLineGap": 28,
   "typoAscent": 776,
   "typoDescent": -185,
   "typoLineGap": 56,
   "winAscent": 932,
   "winDescent": 189,
   "capHeight": 693,
   "xHeight": 520,
   "useTypo": false
  }
 },
 {
  "name": "Zekton",
  "id": "Zekton",
  "asset": "rbxasset://fonts/families/Zekton.json",
  "faces": [],
  "approx": "Jura"
 }
];
