// Generated by tools/build-api.py from rbx-dom reflection database (Roblox API v0.728.0.7280895) — do not edit by hand.
export const API_VERSION = "0.728.0.7280895";
export const CLASSES = {
 "GuiBase2d": {
  "superclass": "GuiBase",
  "creatable": false,
  "props": {
   "AutoLocalize": {
    "type": "Bool"
   },
   "SelectionBehaviorDown": {
    "type": "Enum",
    "enum": "SelectionBehavior"
   },
   "SelectionBehaviorLeft": {
    "type": "Enum",
    "enum": "SelectionBehavior"
   },
   "SelectionBehaviorRight": {
    "type": "Enum",
    "enum": "SelectionBehavior"
   },
   "SelectionBehaviorUp": {
    "type": "Enum",
    "enum": "SelectionBehavior"
   },
   "SelectionGroup": {
    "type": "Bool"
   }
  },
  "defaults": {}
 },
 "GuiObject": {
  "superclass": "GuiBase2d",
  "creatable": false,
  "props": {
   "Active": {
    "type": "Bool"
   },
   "AnchorPoint": {
    "type": "Vector2"
   },
   "AutomaticSize": {
    "type": "Enum",
    "enum": "AutomaticSize"
   },
   "BackgroundColor3": {
    "type": "Color3"
   },
   "BackgroundTransparency": {
    "type": "Float32"
   },
   "BorderColor3": {
    "type": "Color3"
   },
   "BorderMode": {
    "type": "Enum",
    "enum": "BorderMode"
   },
   "BorderSizePixel": {
    "type": "Int32"
   },
   "ClipsDescendants": {
    "type": "Bool"
   },
   "InputSink": {
    "type": "Enum",
    "enum": "InputSink"
   },
   "Interactable": {
    "type": "Bool"
   },
   "LayoutOrder": {
    "type": "Int32"
   },
   "Position": {
    "type": "UDim2"
   },
   "Rotation": {
    "type": "Float32"
   },
   "Selectable": {
    "type": "Bool"
   },
   "SelectionOrder": {
    "type": "Int32"
   },
   "Size": {
    "type": "UDim2"
   },
   "SizeConstraint": {
    "type": "Enum",
    "enum": "SizeConstraint"
   },
   "Visible": {
    "type": "Bool"
   },
   "ZIndex": {
    "type": "Int32"
   }
  },
  "defaults": {}
 },
 "LayerCollector": {
  "superclass": "GuiBase2d",
  "creatable": false,
  "props": {
   "Enabled": {
    "type": "Bool"
   },
   "ResetOnSpawn": {
    "type": "Bool"
   },
   "ZIndexBehavior": {
    "type": "Enum",
    "enum": "ZIndexBehavior"
   }
  },
  "defaults": {}
 },
 "ScreenGui": {
  "superclass": "LayerCollector",
  "creatable": true,
  "props": {
   "ClipToDeviceSafeArea": {
    "type": "Bool"
   },
   "DisplayOrder": {
    "type": "Int32"
   },
   "IgnoreGuiInset": {
    "type": "Bool"
   },
   "SafeAreaCompatibility": {
    "type": "Enum",
    "enum": "SafeAreaCompatibility"
   },
   "ScreenInsets": {
    "type": "Enum",
    "enum": "ScreenInsets"
   }
  },
  "defaults": {
   "AutoLocalize": true,
   "ClipToDeviceSafeArea": true,
   "DisplayOrder": 0,
   "Enabled": true,
   "ResetOnSpawn": true,
   "SafeAreaCompatibility": "FullscreenExtension",
   "ScreenInsets": "CoreUISafeInsets",
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "ZIndexBehavior": "Global"
  }
 },
 "Frame": {
  "superclass": "GuiObject",
  "creatable": true,
  "props": {},
  "defaults": {
   "Active": false,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": false,
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "Rotation": 0.0,
   "Selectable": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "Visible": true,
   "ZIndex": 1
  }
 },
 "ScrollingFrame": {
  "superclass": "GuiObject",
  "creatable": true,
  "props": {
   "AutomaticCanvasSize": {
    "type": "Enum",
    "enum": "AutomaticSize"
   },
   "BottomImage": {
    "type": "ContentId"
   },
   "CanvasSize": {
    "type": "UDim2"
   },
   "ElasticBehavior": {
    "type": "Enum",
    "enum": "ElasticBehavior"
   },
   "HorizontalScrollBarInset": {
    "type": "Enum",
    "enum": "ScrollBarInset"
   },
   "MidImage": {
    "type": "ContentId"
   },
   "ScrollBarImageColor3": {
    "type": "Color3"
   },
   "ScrollBarImageTransparency": {
    "type": "Float32"
   },
   "ScrollBarThickness": {
    "type": "Int32"
   },
   "ScrollingDirection": {
    "type": "Enum",
    "enum": "ScrollingDirection"
   },
   "ScrollingEnabled": {
    "type": "Bool"
   },
   "TopImage": {
    "type": "ContentId"
   },
   "VerticalScrollBarInset": {
    "type": "Enum",
    "enum": "ScrollBarInset"
   },
   "VerticalScrollBarPosition": {
    "type": "Enum",
    "enum": "VerticalScrollBarPosition"
   }
  },
  "defaults": {
   "Active": false,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticCanvasSize": "None",
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "CanvasSize": [
    0.0,
    0,
    2.0,
    0
   ],
   "ClipsDescendants": true,
   "ElasticBehavior": "WhenScrollable",
   "HorizontalScrollBarInset": "None",
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "Rotation": 0.0,
   "ScrollBarImageColor3": "#FFFFFF",
   "ScrollBarImageTransparency": 0.0,
   "ScrollBarThickness": 12,
   "ScrollingDirection": "XY",
   "ScrollingEnabled": true,
   "Selectable": true,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": true,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "VerticalScrollBarInset": "None",
   "VerticalScrollBarPosition": "Right",
   "Visible": true,
   "ZIndex": 1
  }
 },
 "CanvasGroup": {
  "superclass": "GuiObject",
  "creatable": true,
  "props": {
   "GroupColor3": {
    "type": "Color3"
   },
   "GroupTransparency": {
    "type": "Float32"
   }
  },
  "defaults": {
   "Active": false,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": true,
   "GroupColor3": "#FFFFFF",
   "GroupTransparency": 0.0,
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "Rotation": 0.0,
   "Selectable": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "Visible": true,
   "ZIndex": 1
  }
 },
 "GuiLabel": {
  "superclass": "GuiObject",
  "creatable": false,
  "props": {},
  "defaults": {}
 },
 "TextLabel": {
  "superclass": "GuiLabel",
  "creatable": true,
  "props": {
   "FontFace": {
    "type": "Font"
   },
   "LineHeight": {
    "type": "Float32"
   },
   "MaxVisibleGraphemes": {
    "type": "Int32"
   },
   "RichText": {
    "type": "Bool"
   },
   "Text": {
    "type": "String"
   },
   "TextColor3": {
    "type": "Color3"
   },
   "TextDirection": {
    "type": "Enum",
    "enum": "TextDirection"
   },
   "TextScaled": {
    "type": "Bool"
   },
   "TextSize": {
    "type": "Float32"
   },
   "TextStrokeColor3": {
    "type": "Color3"
   },
   "TextStrokeTransparency": {
    "type": "Float32"
   },
   "TextTransparency": {
    "type": "Float32"
   },
   "TextTruncate": {
    "type": "Enum",
    "enum": "TextTruncate"
   },
   "TextWrapped": {
    "type": "Bool"
   },
   "TextXAlignment": {
    "type": "Enum",
    "enum": "TextXAlignment"
   },
   "TextYAlignment": {
    "type": "Enum",
    "enum": "TextYAlignment"
   }
  },
  "defaults": {
   "Active": false,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": false,
   "FontFace": {
    "family": "LegacyArial",
    "weight": "Regular",
    "style": "Normal"
   },
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "LineHeight": 1.0,
   "MaxVisibleGraphemes": -1,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "RichText": false,
   "Rotation": 0.0,
   "Selectable": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "Text": "Label",
   "TextColor3": "#1B2A35",
   "TextDirection": "Auto",
   "TextScaled": false,
   "TextSize": 8.0,
   "TextStrokeColor3": "#000000",
   "TextStrokeTransparency": 1.0,
   "TextTransparency": 0.0,
   "TextTruncate": "None",
   "TextWrapped": false,
   "TextXAlignment": "Center",
   "TextYAlignment": "Center",
   "Visible": true,
   "ZIndex": 1
  }
 },
 "TextButton": {
  "superclass": "GuiButton",
  "creatable": true,
  "props": {
   "FontFace": {
    "type": "Font"
   },
   "LineHeight": {
    "type": "Float32"
   },
   "MaxVisibleGraphemes": {
    "type": "Int32"
   },
   "RichText": {
    "type": "Bool"
   },
   "Text": {
    "type": "String"
   },
   "TextColor3": {
    "type": "Color3"
   },
   "TextDirection": {
    "type": "Enum",
    "enum": "TextDirection"
   },
   "TextScaled": {
    "type": "Bool"
   },
   "TextSize": {
    "type": "Float32"
   },
   "TextStrokeColor3": {
    "type": "Color3"
   },
   "TextStrokeTransparency": {
    "type": "Float32"
   },
   "TextTransparency": {
    "type": "Float32"
   },
   "TextTruncate": {
    "type": "Enum",
    "enum": "TextTruncate"
   },
   "TextWrapped": {
    "type": "Bool"
   },
   "TextXAlignment": {
    "type": "Enum",
    "enum": "TextXAlignment"
   },
   "TextYAlignment": {
    "type": "Enum",
    "enum": "TextYAlignment"
   }
  },
  "defaults": {
   "Active": true,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoButtonColor": true,
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": false,
   "FontFace": {
    "family": "LegacyArial",
    "weight": "Regular",
    "style": "Normal"
   },
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "LineHeight": 1.0,
   "MaxVisibleGraphemes": -1,
   "Modal": false,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "RichText": false,
   "Rotation": 0.0,
   "Selectable": true,
   "Selected": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "Text": "Button",
   "TextColor3": "#1B2A35",
   "TextDirection": "Auto",
   "TextScaled": false,
   "TextSize": 8.0,
   "TextStrokeColor3": "#000000",
   "TextStrokeTransparency": 1.0,
   "TextTransparency": 0.0,
   "TextTruncate": "None",
   "TextWrapped": false,
   "TextXAlignment": "Center",
   "TextYAlignment": "Center",
   "Visible": true,
   "ZIndex": 1
  }
 },
 "TextBox": {
  "superclass": "GuiObject",
  "creatable": true,
  "props": {
   "ClearTextOnFocus": {
    "type": "Bool"
   },
   "FontFace": {
    "type": "Font"
   },
   "LineHeight": {
    "type": "Float32"
   },
   "MaxVisibleGraphemes": {
    "type": "Int32"
   },
   "MultiLine": {
    "type": "Bool"
   },
   "PlaceholderColor3": {
    "type": "Color3"
   },
   "PlaceholderText": {
    "type": "String"
   },
   "RichText": {
    "type": "Bool"
   },
   "Text": {
    "type": "String"
   },
   "TextColor3": {
    "type": "Color3"
   },
   "TextDirection": {
    "type": "Enum",
    "enum": "TextDirection"
   },
   "TextEditable": {
    "type": "Bool"
   },
   "TextScaled": {
    "type": "Bool"
   },
   "TextSize": {
    "type": "Float32"
   },
   "TextStrokeColor3": {
    "type": "Color3"
   },
   "TextStrokeTransparency": {
    "type": "Float32"
   },
   "TextTransparency": {
    "type": "Float32"
   },
   "TextTruncate": {
    "type": "Enum",
    "enum": "TextTruncate"
   },
   "TextWrapped": {
    "type": "Bool"
   },
   "TextXAlignment": {
    "type": "Enum",
    "enum": "TextXAlignment"
   },
   "TextYAlignment": {
    "type": "Enum",
    "enum": "TextYAlignment"
   }
  },
  "defaults": {
   "Active": true,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClearTextOnFocus": true,
   "ClipsDescendants": false,
   "FontFace": {
    "family": "LegacyArial",
    "weight": "Regular",
    "style": "Normal"
   },
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "LineHeight": 1.0,
   "MaxVisibleGraphemes": -1,
   "MultiLine": false,
   "PlaceholderColor3": "#808080",
   "PlaceholderText": "",
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "RichText": false,
   "Rotation": 0.0,
   "Selectable": true,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "Text": "TextBox",
   "TextColor3": "#1B2A35",
   "TextDirection": "Auto",
   "TextEditable": true,
   "TextScaled": false,
   "TextSize": 8.0,
   "TextStrokeColor3": "#000000",
   "TextStrokeTransparency": 1.0,
   "TextTransparency": 0.0,
   "TextTruncate": "None",
   "TextWrapped": false,
   "TextXAlignment": "Center",
   "TextYAlignment": "Center",
   "Visible": true,
   "ZIndex": 1
  }
 },
 "ImageLabel": {
  "superclass": "GuiLabel",
  "creatable": true,
  "props": {
   "Image": {
    "type": "ContentId"
   },
   "ImageColor3": {
    "type": "Color3"
   },
   "ImageRectOffset": {
    "type": "Vector2"
   },
   "ImageRectSize": {
    "type": "Vector2"
   },
   "ImageTransparency": {
    "type": "Float32"
   },
   "ResampleMode": {
    "type": "Enum",
    "enum": "ResamplerMode"
   },
   "ScaleType": {
    "type": "Enum",
    "enum": "ScaleType"
   },
   "SliceCenter": {
    "type": "Rect"
   },
   "SliceScale": {
    "type": "Float32"
   },
   "TileSize": {
    "type": "UDim2"
   }
  },
  "defaults": {
   "Active": false,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": false,
   "ImageColor3": "#FFFFFF",
   "ImageRectOffset": [
    0.0,
    0.0
   ],
   "ImageRectSize": [
    0.0,
    0.0
   ],
   "ImageTransparency": 0.0,
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "ResampleMode": "Default",
   "Rotation": 0.0,
   "ScaleType": "Stretch",
   "Selectable": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "SliceCenter": [
    0.0,
    0.0,
    0.0,
    0.0
   ],
   "SliceScale": 1.0,
   "TileSize": [
    1.0,
    0,
    1.0,
    0
   ],
   "Visible": true,
   "ZIndex": 1
  }
 },
 "ImageButton": {
  "superclass": "GuiButton",
  "creatable": true,
  "props": {
   "HoverImage": {
    "type": "ContentId"
   },
   "Image": {
    "type": "ContentId"
   },
   "ImageColor3": {
    "type": "Color3"
   },
   "ImageRectOffset": {
    "type": "Vector2"
   },
   "ImageRectSize": {
    "type": "Vector2"
   },
   "ImageTransparency": {
    "type": "Float32"
   },
   "PressedImage": {
    "type": "ContentId"
   },
   "ResampleMode": {
    "type": "Enum",
    "enum": "ResamplerMode"
   },
   "ScaleType": {
    "type": "Enum",
    "enum": "ScaleType"
   },
   "SliceCenter": {
    "type": "Rect"
   },
   "SliceScale": {
    "type": "Float32"
   },
   "TileSize": {
    "type": "UDim2"
   }
  },
  "defaults": {
   "Active": true,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoButtonColor": true,
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": false,
   "ImageColor3": "#FFFFFF",
   "ImageRectOffset": [
    0.0,
    0.0
   ],
   "ImageRectSize": [
    0.0,
    0.0
   ],
   "ImageTransparency": 0.0,
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "Modal": false,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "ResampleMode": "Default",
   "Rotation": 0.0,
   "ScaleType": "Stretch",
   "Selectable": true,
   "Selected": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "SliceCenter": [
    0.0,
    0.0,
    0.0,
    0.0
   ],
   "SliceScale": 1.0,
   "TileSize": [
    1.0,
    0,
    1.0,
    0
   ],
   "Visible": true,
   "ZIndex": 1
  }
 },
 "GuiButton": {
  "superclass": "GuiObject",
  "creatable": false,
  "props": {
   "AutoButtonColor": {
    "type": "Bool"
   },
   "Modal": {
    "type": "Bool"
   },
   "Selected": {
    "type": "Bool"
   }
  },
  "defaults": {}
 },
 "ViewportFrame": {
  "superclass": "GuiObject",
  "creatable": true,
  "props": {
   "Ambient": {
    "type": "Color3"
   },
   "ImageColor3": {
    "type": "Color3"
   },
   "ImageTransparency": {
    "type": "Float32"
   },
   "LightColor": {
    "type": "Color3"
   },
   "LightDirection": {
    "type": "Vector3"
   }
  },
  "defaults": {
   "Active": false,
   "Ambient": "#C8C8C8",
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": false,
   "ImageColor3": "#FFFFFF",
   "ImageTransparency": 0.0,
   "InputSink": "None",
   "Interactable": true,
   "LayoutOrder": 0,
   "LightColor": "#8C8C8C",
   "LightDirection": [
    -1.0,
    -1.0,
    -1.0
   ],
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "Rotation": 0.0,
   "Selectable": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "Visible": true,
   "ZIndex": 1
  }
 },
 "VideoFrame": {
  "superclass": "GuiObject",
  "creatable": true,
  "props": {
   "InternalVideoUsage": {
    "type": "Enum",
    "enum": "InternalVideoUsage"
   },
   "Looped": {
    "type": "Bool"
   },
   "MaximumResolution": {
    "type": "Enum",
    "enum": "VideoSampleSize"
   },
   "Playing": {
    "type": "Bool"
   },
   "RollOffMaxDistance": {
    "type": "Float32"
   },
   "RollOffMinDistance": {
    "type": "Float32"
   },
   "RollOffMode": {
    "type": "Enum",
    "enum": "RollOffMode"
   },
   "TimePosition": {
    "type": "Float64"
   },
   "Video": {
    "type": "ContentId"
   },
   "Volume": {
    "type": "Float32"
   }
  },
  "defaults": {
   "Active": false,
   "AnchorPoint": [
    0.0,
    0.0
   ],
   "AutoLocalize": true,
   "AutomaticSize": "None",
   "BackgroundColor3": "#A3A2A5",
   "BackgroundTransparency": 0.0,
   "BorderColor3": "#1B2A35",
   "BorderMode": "Outline",
   "BorderSizePixel": 1,
   "ClipsDescendants": false,
   "InputSink": "None",
   "Interactable": true,
   "InternalVideoUsage": "Default",
   "LayoutOrder": 0,
   "Looped": false,
   "MaximumResolution": "Full",
   "Playing": false,
   "Position": [
    0.0,
    0,
    0.0,
    0
   ],
   "RollOffMaxDistance": 10000.0,
   "RollOffMinDistance": 1.0,
   "RollOffMode": "Inverse",
   "Rotation": 0.0,
   "Selectable": false,
   "SelectionBehaviorDown": "Escape",
   "SelectionBehaviorLeft": "Escape",
   "SelectionBehaviorRight": "Escape",
   "SelectionBehaviorUp": "Escape",
   "SelectionGroup": false,
   "SelectionOrder": 0,
   "Size": [
    0.0,
    0,
    0.0,
    0
   ],
   "SizeConstraint": "RelativeXY",
   "TimePosition": 0.0,
   "Visible": true,
   "Volume": 1.0,
   "ZIndex": 1
  }
 },
 "Folder": {
  "superclass": "Instance",
  "creatable": true,
  "props": {},
  "defaults": {}
 },
 "UICorner": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "BottomLeftRadius": {
    "type": "UDim"
   },
   "BottomRightRadius": {
    "type": "UDim"
   },
   "CornerRadius": {
    "type": "UDim"
   },
   "TopLeftRadius": {
    "type": "UDim"
   },
   "TopRightRadius": {
    "type": "UDim"
   }
  },
  "defaults": {
   "BottomLeftRadius": [
    0.0,
    8
   ],
   "BottomRightRadius": [
    0.0,
    8
   ],
   "TopLeftRadius": [
    0.0,
    8
   ],
   "TopRightRadius": [
    0.0,
    8
   ]
  }
 },
 "UIStroke": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "ApplyStrokeMode": {
    "type": "Enum",
    "enum": "ApplyStrokeMode"
   },
   "BorderOffset": {
    "type": "UDim"
   },
   "BorderStrokePosition": {
    "type": "Enum",
    "enum": "BorderStrokePosition"
   },
   "Color": {
    "type": "Color3"
   },
   "Enabled": {
    "type": "Bool"
   },
   "LineJoinMode": {
    "type": "Enum",
    "enum": "LineJoinMode"
   },
   "StrokeSizingMode": {
    "type": "Enum",
    "enum": "StrokeSizingMode"
   },
   "Thickness": {
    "type": "Float32"
   },
   "Transparency": {
    "type": "Float32"
   },
   "ZIndex": {
    "type": "Int32"
   }
  },
  "defaults": {
   "ApplyStrokeMode": "Contextual",
   "BorderOffset": [
    0.0,
    0
   ],
   "BorderStrokePosition": "Outer",
   "Color": "#000000",
   "Enabled": true,
   "LineJoinMode": "Round",
   "StrokeSizingMode": "FixedSize",
   "Thickness": 1.0,
   "Transparency": 0.0,
   "ZIndex": 1
  }
 },
 "UIGradient": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "Color": {
    "type": "ColorSequence"
   },
   "Enabled": {
    "type": "Bool"
   },
   "Offset": {
    "type": "Vector2"
   },
   "Rotation": {
    "type": "Float32"
   },
   "Scale": {
    "type": "Float32"
   },
   "TileMode": {
    "type": "Enum",
    "enum": "GradientTileMode"
   },
   "Transparency": {
    "type": "NumberSequence"
   },
   "Type": {
    "type": "Enum",
    "enum": "GradientType"
   }
  },
  "defaults": {
   "Color": [
    [
     0.0,
     "#FFFFFF"
    ],
    [
     1.0,
     "#FFFFFF"
    ]
   ],
   "Enabled": true,
   "Offset": [
    0.0,
    0.0
   ],
   "Rotation": 0.0,
   "Scale": 1.0,
   "TileMode": "Clamp",
   "Transparency": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.0
    ]
   ],
   "Type": "Linear"
  }
 },
 "UIPadding": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "PaddingBottom": {
    "type": "UDim"
   },
   "PaddingLeft": {
    "type": "UDim"
   },
   "PaddingRight": {
    "type": "UDim"
   },
   "PaddingTop": {
    "type": "UDim"
   }
  },
  "defaults": {
   "PaddingBottom": [
    0.0,
    0
   ],
   "PaddingLeft": [
    0.0,
    0
   ],
   "PaddingRight": [
    0.0,
    0
   ],
   "PaddingTop": [
    0.0,
    0
   ]
  }
 },
 "UIScale": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "Scale": {
    "type": "Float32"
   }
  },
  "defaults": {
   "Scale": 1.0
  }
 },
 "UIShadow": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "BlurRadius": {
    "type": "UDim"
   },
   "Color": {
    "type": "Color3"
   },
   "Enabled": {
    "type": "Bool"
   },
   "Offset": {
    "type": "UDim2"
   },
   "Spread": {
    "type": "UDim2"
   },
   "Transparency": {
    "type": "Float32"
   },
   "ZIndex": {
    "type": "Int32"
   }
  },
  "defaults": {
   "BlurRadius": [
    0.0,
    0
   ],
   "Color": "#000000",
   "Enabled": true,
   "Offset": [
    0.0,
    0,
    0.0,
    0
   ],
   "Spread": [
    0.0,
    0,
    0.0,
    0
   ],
   "Transparency": 0.0,
   "ZIndex": -1
  }
 },
 "UIAspectRatioConstraint": {
  "superclass": "UIConstraint",
  "creatable": true,
  "props": {
   "AspectRatio": {
    "type": "Float32"
   },
   "AspectType": {
    "type": "Enum",
    "enum": "AspectType"
   },
   "DominantAxis": {
    "type": "Enum",
    "enum": "DominantAxis"
   }
  },
  "defaults": {
   "AspectRatio": 1.0,
   "AspectType": "FitWithinMaxSize",
   "DominantAxis": "Width"
  }
 },
 "UISizeConstraint": {
  "superclass": "UIConstraint",
  "creatable": true,
  "props": {
   "MaxSize": {
    "type": "Vector2"
   },
   "MinSize": {
    "type": "Vector2"
   }
  },
  "defaults": {
   "MaxSize": [
    null,
    null
   ],
   "MinSize": [
    0.0,
    0.0
   ]
  }
 },
 "UITextSizeConstraint": {
  "superclass": "UIConstraint",
  "creatable": true,
  "props": {
   "MaxTextSize": {
    "type": "Int32"
   },
   "MinTextSize": {
    "type": "Int32"
   }
  },
  "defaults": {
   "MaxTextSize": 100,
   "MinTextSize": 1
  }
 },
 "UIListLayout": {
  "superclass": "UIGridStyleLayout",
  "creatable": true,
  "props": {
   "HorizontalFlex": {
    "type": "Enum",
    "enum": "UIFlexAlignment"
   },
   "ItemLineAlignment": {
    "type": "Enum",
    "enum": "ItemLineAlignment"
   },
   "Padding": {
    "type": "UDim"
   },
   "VerticalFlex": {
    "type": "Enum",
    "enum": "UIFlexAlignment"
   },
   "Wraps": {
    "type": "Bool"
   }
  },
  "defaults": {
   "FillDirection": "Vertical",
   "HorizontalAlignment": "Left",
   "HorizontalFlex": "None",
   "ItemLineAlignment": "Automatic",
   "Padding": [
    0.0,
    0
   ],
   "SortOrder": "Name",
   "VerticalAlignment": "Top",
   "VerticalFlex": "None",
   "Wraps": false
  }
 },
 "UIGridLayout": {
  "superclass": "UIGridStyleLayout",
  "creatable": true,
  "props": {
   "CellPadding": {
    "type": "UDim2"
   },
   "CellSize": {
    "type": "UDim2"
   },
   "FillDirectionMaxCells": {
    "type": "Int32"
   },
   "StartCorner": {
    "type": "Enum",
    "enum": "StartCorner"
   }
  },
  "defaults": {
   "CellPadding": [
    0.0,
    5,
    0.0,
    5
   ],
   "CellSize": [
    0.0,
    100,
    0.0,
    100
   ],
   "FillDirection": "Horizontal",
   "FillDirectionMaxCells": 0,
   "HorizontalAlignment": "Left",
   "SortOrder": "Name",
   "StartCorner": "TopLeft",
   "VerticalAlignment": "Top"
  }
 },
 "UIGridStyleLayout": {
  "superclass": "UILayout",
  "creatable": false,
  "props": {
   "FillDirection": {
    "type": "Enum",
    "enum": "FillDirection"
   },
   "HorizontalAlignment": {
    "type": "Enum",
    "enum": "HorizontalAlignment"
   },
   "SortOrder": {
    "type": "Enum",
    "enum": "SortOrder"
   },
   "VerticalAlignment": {
    "type": "Enum",
    "enum": "VerticalAlignment"
   }
  },
  "defaults": {}
 },
 "UIPageLayout": {
  "superclass": "UIGridStyleLayout",
  "creatable": true,
  "props": {
   "Animated": {
    "type": "Bool"
   },
   "Circular": {
    "type": "Bool"
   },
   "EasingDirection": {
    "type": "Enum",
    "enum": "EasingDirection"
   },
   "EasingStyle": {
    "type": "Enum",
    "enum": "EasingStyle"
   },
   "GamepadInputEnabled": {
    "type": "Bool"
   },
   "Padding": {
    "type": "UDim"
   },
   "ScrollWheelInputEnabled": {
    "type": "Bool"
   },
   "TouchInputEnabled": {
    "type": "Bool"
   },
   "TweenTime": {
    "type": "Float32"
   }
  },
  "defaults": {
   "Animated": true,
   "Circular": false,
   "EasingDirection": "Out",
   "EasingStyle": "Back",
   "FillDirection": "Horizontal",
   "GamepadInputEnabled": true,
   "HorizontalAlignment": "Left",
   "Padding": [
    0.0,
    0
   ],
   "ScrollWheelInputEnabled": true,
   "SortOrder": "Name",
   "TouchInputEnabled": true,
   "TweenTime": 1.0,
   "VerticalAlignment": "Top"
  }
 },
 "UIFlexItem": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "FlexMode": {
    "type": "Enum",
    "enum": "UIFlexMode"
   },
   "GrowRatio": {
    "type": "Float32"
   },
   "ItemLineAlignment": {
    "type": "Enum",
    "enum": "ItemLineAlignment"
   },
   "ShrinkRatio": {
    "type": "Float32"
   }
  },
  "defaults": {
   "FlexMode": "None",
   "GrowRatio": 0.0,
   "ItemLineAlignment": "Automatic",
   "ShrinkRatio": 0.0
  }
 },
 "UIDragDetector": {
  "superclass": "UIComponent",
  "creatable": true,
  "props": {
   "ActivatedCursorIcon": {
    "type": "ContentId"
   },
   "BoundingBehavior": {
    "type": "Enum",
    "enum": "UIDragDetectorBoundingBehavior"
   },
   "CursorIcon": {
    "type": "ContentId"
   },
   "DragAxis": {
    "type": "Vector2"
   },
   "DragRelativity": {
    "type": "Enum",
    "enum": "UIDragDetectorDragRelativity"
   },
   "DragRotation": {
    "type": "Float32"
   },
   "DragSpace": {
    "type": "Enum",
    "enum": "UIDragDetectorDragSpace"
   },
   "DragStyle": {
    "type": "Enum",
    "enum": "UIDragDetectorDragStyle"
   },
   "DragUDim2": {
    "type": "UDim2"
   },
   "Enabled": {
    "type": "Bool"
   },
   "MaxDragAngle": {
    "type": "Float32"
   },
   "MaxDragTranslation": {
    "type": "UDim2"
   },
   "MinDragAngle": {
    "type": "Float32"
   },
   "MinDragTranslation": {
    "type": "UDim2"
   },
   "ResponseStyle": {
    "type": "Enum",
    "enum": "UIDragDetectorResponseStyle"
   },
   "SelectionModeDragSpeed": {
    "type": "UDim2"
   },
   "SelectionModeRotateSpeed": {
    "type": "Float32"
   },
   "UIDragSpeedAxisMapping": {
    "type": "Enum",
    "enum": "UIDragSpeedAxisMapping"
   }
  },
  "defaults": {
   "BoundingBehavior": "Automatic",
   "DragAxis": [
    1.0,
    0.0
   ],
   "DragRelativity": "Absolute",
   "DragRotation": 0.0,
   "DragSpace": "Parent",
   "DragStyle": "TranslatePlane",
   "DragUDim2": [
    0.0,
    0,
    0.0,
    0
   ],
   "Enabled": true,
   "MaxDragAngle": 0.0,
   "MaxDragTranslation": [
    0.0,
    0,
    0.0,
    0
   ],
   "MinDragAngle": 0.0,
   "MinDragTranslation": [
    0.0,
    0,
    0.0,
    0
   ],
   "ResponseStyle": "Offset",
   "SelectionModeDragSpeed": [
    0.0,
    300,
    0.0,
    300
   ],
   "SelectionModeRotateSpeed": 90.0,
   "UIDragSpeedAxisMapping": "XY"
  }
 },
 "LocalScript": {
  "superclass": "Script",
  "creatable": true,
  "props": {},
  "defaults": {}
 },
 "ModuleScript": {
  "superclass": "LuaSourceContainer",
  "creatable": true,
  "props": {},
  "defaults": {}
 }
};
export const ENUMS = {
 "ApplyStrokeMode": {
  "Contextual": 0,
  "Border": 1
 },
 "AspectType": {
  "FitWithinMaxSize": 0,
  "ScaleWithParentSize": 1
 },
 "AutomaticSize": {
  "None": 0,
  "X": 1,
  "Y": 2,
  "XY": 3
 },
 "BorderMode": {
  "Outline": 0,
  "Middle": 1,
  "Inset": 2
 },
 "BorderStrokePosition": {
  "Outer": 0,
  "Center": 1,
  "Inner": 2
 },
 "DominantAxis": {
  "Width": 0,
  "Height": 1
 },
 "EasingDirection": {
  "In": 0,
  "Out": 1,
  "InOut": 2
 },
 "EasingStyle": {
  "Linear": 0,
  "Sine": 1,
  "Back": 2,
  "Quad": 3,
  "Quart": 4,
  "Quint": 5,
  "Bounce": 6,
  "Elastic": 7,
  "Exponential": 8,
  "Circular": 9,
  "Cubic": 10
 },
 "ElasticBehavior": {
  "WhenScrollable": 0,
  "Always": 1,
  "Never": 2
 },
 "FillDirection": {
  "Horizontal": 0,
  "Vertical": 1
 },
 "FontStyle": {
  "Normal": 0,
  "Italic": 1
 },
 "FontWeight": {
  "Thin": 100,
  "ExtraLight": 200,
  "Light": 300,
  "Regular": 400,
  "Medium": 500,
  "SemiBold": 600,
  "Bold": 700,
  "ExtraBold": 800,
  "Heavy": 900
 },
 "GradientTileMode": {
  "Clamp": 0,
  "Repeat": 1,
  "Mirror": 2
 },
 "GradientType": {
  "Linear": 0,
  "Radial": 1,
  "Conical": 2
 },
 "HorizontalAlignment": {
  "Center": 0,
  "Left": 1,
  "Right": 2
 },
 "InputSink": {
  "None": 0,
  "Activate": 1,
  "All": 100
 },
 "InternalVideoUsage": {
  "Default": 0,
  "WatchPage": 1,
  "HomeCarousel": 2
 },
 "ItemLineAlignment": {
  "Automatic": 0,
  "Start": 1,
  "Center": 2,
  "End": 3,
  "Stretch": 4
 },
 "LineJoinMode": {
  "Round": 0,
  "Bevel": 1,
  "Miter": 2
 },
 "ResamplerMode": {
  "Default": 0,
  "Pixelated": 1
 },
 "RollOffMode": {
  "Inverse": 0,
  "Linear": 1,
  "LinearSquare": 2,
  "InverseTapered": 3
 },
 "SafeAreaCompatibility": {
  "None": 0,
  "FullscreenExtension": 1
 },
 "ScaleType": {
  "Stretch": 0,
  "Slice": 1,
  "Tile": 2,
  "Fit": 3,
  "Crop": 4
 },
 "ScreenInsets": {
  "None": 0,
  "DeviceSafeInsets": 1,
  "CoreUISafeInsets": 2,
  "TopbarSafeInsets": 3
 },
 "ScrollBarInset": {
  "None": 0,
  "ScrollBar": 1,
  "Always": 2
 },
 "ScrollingDirection": {
  "X": 1,
  "Y": 2,
  "XY": 4
 },
 "SelectionBehavior": {
  "Escape": 0,
  "Stop": 1
 },
 "SizeConstraint": {
  "RelativeXY": 0,
  "RelativeXX": 1,
  "RelativeYY": 2
 },
 "SortOrder": {
  "Name": 0,
  "Custom": 1,
  "LayoutOrder": 2
 },
 "StartCorner": {
  "TopLeft": 0,
  "TopRight": 1,
  "BottomLeft": 2,
  "BottomRight": 3
 },
 "StrokeSizingMode": {
  "FixedSize": 0,
  "ScaledSize": 1
 },
 "TextDirection": {
  "Auto": 0,
  "LeftToRight": 1,
  "RightToLeft": 2
 },
 "TextTruncate": {
  "None": 0,
  "AtEnd": 1,
  "SplitWord": 2
 },
 "TextXAlignment": {
  "Left": 0,
  "Right": 1,
  "Center": 2
 },
 "TextYAlignment": {
  "Top": 0,
  "Center": 1,
  "Bottom": 2
 },
 "UIDragDetectorBoundingBehavior": {
  "Automatic": 0,
  "EntireObject": 1,
  "HitPoint": 2
 },
 "UIDragDetectorDragRelativity": {
  "Absolute": 0,
  "Relative": 1
 },
 "UIDragDetectorDragSpace": {
  "Parent": 0,
  "LayerCollector": 1,
  "Reference": 2
 },
 "UIDragDetectorDragStyle": {
  "TranslatePlane": 0,
  "TranslateLine": 1,
  "Rotate": 2,
  "Scriptable": 3
 },
 "UIDragDetectorResponseStyle": {
  "Offset": 0,
  "Scale": 1,
  "CustomOffset": 2,
  "CustomScale": 3
 },
 "UIDragSpeedAxisMapping": {
  "XY": 0,
  "XX": 1,
  "YY": 2
 },
 "UIFlexAlignment": {
  "None": 0,
  "Fill": 1,
  "SpaceAround": 2,
  "SpaceBetween": 3,
  "SpaceEvenly": 4
 },
 "UIFlexMode": {
  "None": 0,
  "Grow": 1,
  "Shrink": 2,
  "Fill": 3,
  "Custom": 4
 },
 "VerticalAlignment": {
  "Center": 0,
  "Top": 1,
  "Bottom": 2
 },
 "VerticalScrollBarPosition": {
  "Right": 0,
  "Left": 1
 },
 "VideoSampleSize": {
  "Small": 0,
  "Medium": 1,
  "Large": 2,
  "Full": 3
 },
 "ZIndexBehavior": {
  "Global": 0,
  "Sibling": 1
 }
};
