#!/usr/bin/env python3
"""Generates app/js/core/rbx-api.js from rbx-dom's reflection database.

Usage: python3 tools/build-api.py <path to rbx-dom/rbx_dom_lua/src/database.json>
Only the UI classes/properties the editor supports are extracted, with their
exact data types, enum values and Instance.new() defaults.
"""
import json, os, sys

db = json.load(open(sys.argv[1]))
C, E = db['Classes'], db['Enums']
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CLASSES = ['GuiBase2d', 'GuiObject', 'LayerCollector', 'ScreenGui', 'Frame', 'ScrollingFrame', 'CanvasGroup',
           'GuiLabel', 'TextLabel', 'TextButton', 'TextBox', 'ImageLabel', 'ImageButton', 'GuiButton',
           'ViewportFrame', 'VideoFrame', 'Folder',
           'UICorner', 'UIStroke', 'UIGradient', 'UIPadding', 'UIScale', 'UIShadow',
           'UIAspectRatioConstraint', 'UISizeConstraint', 'UITextSizeConstraint',
           'UIListLayout', 'UIGridLayout', 'UIGridStyleLayout', 'UIPageLayout', 'UIFlexItem',
           'UIDragDetector', 'LocalScript', 'ModuleScript']
SKIP_TYPES = {'BrickColor', 'Ref', 'Content', 'Attributes', 'Tags', 'UniqueId', 'SecurityCapabilities', 'Int64', 'BinaryString', 'SharedString'}
SKIP_PROPS = {'FontSize', 'Font', 'TextWrap', 'Style', 'Draggable', 'Archivable', 'Sandboxed', 'Localize',
              'RootLocalizationTable', 'SelectionImageObject', 'NextSelectionDown', 'NextSelectionUp', 'NextSelectionLeft',
              'NextSelectionRight', 'CursorPosition', 'SelectionStart', 'CanvasPosition', 'Source', 'LinkedSource',
              'OpenTypeFeatures', 'Confidential', 'TextColor', 'ShowNativeInput'}

def ptype(p):
    dt = p['DataType']
    return ('Enum', dt['Enum']) if 'Enum' in dt else (dt['Value'], None)

def conv_default(v):
    (k, val), = v.items()
    if k == 'Color3':
        return '#%02X%02X%02X' % tuple(round(max(0, min(1, c)) * 255) for c in val)
    if k == 'UDim2':
        return [val[0][0], val[0][1], val[1][0], val[1][1]]
    if k == 'UDim':
        return [val[0], val[1]]
    if k == 'Rect':
        return [val[0][0], val[0][1], val[1][0], val[1][1]]
    if k == 'ColorSequence':
        return [[kp['time'], conv_default({'Color3': kp['color']})] for kp in val['keypoints']]
    if k == 'NumberSequence':
        return [[kp['time'], kp['value']] for kp in val['keypoints']]
    if k == 'Font':
        fam = val['family'].rsplit('/', 1)[-1].replace('.json', '')
        return {'family': fam, 'weight': val['weight'], 'style': val['style']}
    if k in ('ContentId',):
        return val or ''
    return val

out_classes, used_enums = {}, set()
for n in CLASSES:
    c = C[n]
    props = {}
    for pn, p in c['Properties'].items():
        if p.get('Scriptability') != 'ReadWrite' or pn in SKIP_PROPS or (n == 'GuiObject' and pn == 'Transparency'):
            continue
        t, en = ptype(p)
        if t in SKIP_TYPES:
            continue
        if pn.endswith('Content') and t == 'Content':
            continue
        props[pn] = {'type': t} if not en else {'type': 'Enum', 'enum': en}
        if en:
            used_enums.add(en)
    defaults = {}
    for pn, v in c.get('DefaultProperties', {}).items():
        try:
            defaults[pn] = conv_default(v)
        except Exception:
            pass
    tags = c.get('Tags') or []
    out_classes[n] = {'superclass': c.get('Superclass'), 'creatable': 'NotCreatable' not in tags, 'props': props, 'defaults': defaults}

# Only keep defaults for props we know about anywhere in the chain
def chain(n):
    while n in out_classes:
        yield n
        n = out_classes[n]['superclass']
for n, c in out_classes.items():
    known = set()
    for a in chain(n):
        known |= set(out_classes[a]['props'])
    known.add('Name')
    c['defaults'] = {k: v for k, v in c['defaults'].items() if k in known}
    # enum defaults -> item names
    for a in chain(n):
        for pn, pd in out_classes[a]['props'].items():
            if pd['type'] == 'Enum' and isinstance(c['defaults'].get(pn), int):
                inv = {v: k for k, v in E[pd['enum']]['items'].items()}
                c['defaults'][pn] = inv.get(c['defaults'][pn], c['defaults'][pn])

used_enums |= {'EasingStyle', 'EasingDirection', 'FontWeight', 'FontStyle'}
enums = {n: dict(sorted(E[n]['items'].items(), key=lambda kv: kv[1])) for n in sorted(used_enums) if n in E}

js = ('// Generated by tools/build-api.py from rbx-dom reflection database (Roblox API v'
      + '.'.join(map(str, db['Version'])) + ') — do not edit by hand.\n'
      'export const API_VERSION = ' + json.dumps('.'.join(map(str, db['Version']))) + ';\n'
      'export const CLASSES = ' + json.dumps(out_classes, indent=1) + ';\n'
      'export const ENUMS = ' + json.dumps(enums, indent=1) + ';\n')
open(os.path.join(ROOT, 'app', 'js', 'core', 'rbx-api.js'), 'w').write(js)
print(len(out_classes), 'classes', len(enums), 'enums', sum(len(c['props']) for c in out_classes.values()), 'props')
