#!/usr/bin/env python3
"""Builds app/fonts/* and app/js/core/fonts-data.js from @fontsource npm packages.

Usage: python3 tools/build-fonts.py <dir-with-extracted-fontsource-packages>
Each package is expected at <dir>/<pkg>/package/files/<pkg>-latin-<w>-<style>.woff2
Only OFL fonts available on npm are bundled; Roblox-only fonts (Builder, Zekton...)
fall back to a similar bundled font in the editor preview (see `approx`).
"""
import json, os, re, shutil, sys
from fontTools.ttLib import TTFont

SRC = sys.argv[1]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'app', 'fonts')

# Official Roblox font families (Datatype.Font docs, creator-docs). id = json file stem.
FAMILIES = [
  ('Accanthis ADF Std', 'AccanthisADFStd', None, 'Merriweather'),
  ('Amatic SC', 'AmaticSC', 'amatic-sc', None),
  ('Arimo', 'Arimo', 'arimo', None),
  ('Balthazar', 'Balthazar', 'balthazar', None),
  ('Bangers', 'Bangers', 'bangers', None),
  ('Builder Extended', 'BuilderExtended', None, 'Michroma'),
  ('Builder Mono', 'BuilderMono', None, 'Roboto Mono'),
  ('Builder Sans', 'BuilderSans', None, 'Arimo'),
  ('Comic Neue Angular', 'ComicNeueAngular', 'comic-neue', None),
  ('Creepster', 'Creepster', 'creepster', None),
  ('Denk One', 'DenkOne', 'denk-one', None),
  ('Fondamento', 'Fondamento', 'fondamento', None),
  ('Fredoka One', 'FredokaOne', 'fredoka-one', None),
  ('Grenze Gotisch', 'GrenzeGotisch', 'grenze-gotisch', None),
  ('Guru', 'Guru', None, 'Merriweather'),
  ('Highway Gothic', 'HighwayGothic', None, 'Roboto Condensed'),
  ('Inconsolata', 'Inconsolata', 'inconsolata', None),
  ('Indie Flower', 'IndieFlower', 'indie-flower', None),
  ('Josefin Sans', 'JosefinSans', 'josefin-sans', None),
  ('Jura', 'Jura', 'jura', None),
  ('Kalam', 'Kalam', 'kalam', None),
  ('Luckiest Guy', 'LuckiestGuy', 'luckiest-guy', None),
  ('Merriweather', 'Merriweather', 'merriweather', None),
  ('Michroma', 'Michroma', 'michroma', None),
  ('Montserrat', 'Montserrat', 'montserrat', None),
  ('Nunito', 'Nunito', 'nunito', None),
  ('Oswald', 'Oswald', 'oswald', None),
  ('Patrick Hand', 'PatrickHand', 'patrick-hand', None),
  ('Permanent Marker', 'PermanentMarker', 'permanent-marker', None),
  ('Press Start 2P', 'PressStart2P', 'press-start-2p', None),
  ('Roboto', 'Roboto', 'roboto', None),
  ('Roboto Condensed', 'RobotoCondensed', 'roboto-condensed', None),
  ('Roboto Mono', 'RobotoMono', 'roboto-mono', None),
  ('Roman Antique', 'RomanAntique', None, 'Fondamento'),
  ('Sarpanch', 'Sarpanch', 'sarpanch', None),
  ('Source Sans Pro', 'SourceSansPro', 'source-sans-pro', None),
  ('Special Elite', 'SpecialElite', 'special-elite', None),
  ('Titillium Web', 'TitilliumWeb', 'titillium-web', None),
  ('Ubuntu', 'Ubuntu', 'ubuntu', None),
  ('Zekton', 'Zekton', None, 'Jura'),
]

def metrics(path):
    f = TTFont(path)
    head, hhea, os2 = f['head'], f['hhea'], f['OS/2']
    return {
        'upm': head.unitsPerEm,
        'hheaAscent': hhea.ascent, 'hheaDescent': hhea.descent, 'hheaLineGap': hhea.lineGap,
        'typoAscent': os2.sTypoAscender, 'typoDescent': os2.sTypoDescender, 'typoLineGap': os2.sTypoLineGap,
        'winAscent': os2.usWinAscent, 'winDescent': os2.usWinDescent,
        'capHeight': getattr(os2, 'sCapHeight', 0), 'xHeight': getattr(os2, 'sxHeight', 0),
        'useTypo': bool(os2.fsSelection & (1 << 7)),
    }

out = []
if os.path.isdir(OUT):
    shutil.rmtree(OUT)
os.makedirs(OUT)
for name, fid, pkg, approx in FAMILIES:
    entry = {'name': name, 'id': fid, 'asset': f'rbxasset://fonts/families/{fid}.json', 'faces': [], 'approx': approx}
    if pkg:
        files = os.path.join(SRC, pkg, 'package', 'files')
        rx = re.compile(rf'^{re.escape(pkg)}-latin-(\d+)-(normal|italic)\.woff2$')
        os.makedirs(os.path.join(OUT, fid), exist_ok=True)
        for fn in sorted(os.listdir(files)):
            m = rx.match(fn)
            if not m:
                continue
            w, st = int(m.group(1)), m.group(2)
            dst = f'{w}-{st}.woff2'
            shutil.copy(os.path.join(files, fn), os.path.join(OUT, fid, dst))
            entry['faces'].append({'weight': w, 'style': 'Italic' if st == 'italic' else 'Normal', 'file': f'{fid}/{dst}'})
        reg = next((f for f in entry['faces'] if f['style'] == 'Normal' and f['weight'] == 400), None) or entry['faces'][0]
        entry['metrics'] = metrics(os.path.join(OUT, reg['file']))
        lic = os.path.join(SRC, pkg, 'package', 'LICENSE')
        if os.path.exists(lic):
            shutil.copy(lic, os.path.join(OUT, fid, 'LICENSE'))
    out.append(entry)

js = ('// Generated by tools/build-fonts.py — do not edit by hand.\n'
      '// Official Roblox font families (rbxasset://fonts/families/*.json).\n'
      'export const FONT_FAMILIES = ' + json.dumps(out, indent=1) + ';\n')
open(os.path.join(ROOT, 'app', 'js', 'core', 'fonts-data.js'), 'w').write(js)
print('families', len(out), 'bundled', sum(1 for e in out if e['faces']))
